//! The schema and seed files a deployment needs, in the order they must be applied.
//!
//! Applying the schema is the one real asymmetry between Supabase cloud and a self-hosted
//! stack: cloud has a Management API that accepts SQL, self-hosted has none, and this
//! client deliberately speaks only `PostgREST` over HTTP (see `CLAUDE.md`). Rather than
//! teach the tool a second, unlike access path with credentials it cannot validate, this
//! module owns the part that actually goes wrong — **the order** — and lets the operator
//! choose how the SQL reaches their database.
//!
//! The files are `include_str!`'d rather than read from disk so that
//! `nuanalytics db bootstrap --print` works for someone who installed the binary and has
//! no checkout. Embedding also means there is exactly one copy of each file: editing
//! `docs/database/schema.sql` changes what the tool emits, with no chance of drift.

use std::fmt::Write as _;

/// One schema or seed file, with why it has to be applied where it is.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SchemaFile {
    /// Path relative to the repository root, as the docs refer to it.
    pub path: &'static str,
    /// What applying this file achieves, for the progress output.
    pub purpose: &'static str,
    /// The file's contents, embedded at compile time.
    pub sql: &'static str,
}

/// The five files, in the only order that works.
///
/// The ordering is not stylistic. `cip-seed.sql` and `lookup-seed.sql` insert into tables
/// `schema.sql` creates, and `program-lookup-seed.sql` seeds `degree_types`, which
/// `programs-schema.sql` creates. Running them out of order fails on a missing relation,
/// which is a confusing way to discover a documented sequence.
pub const SCHEMA_FILES: [SchemaFile; 5] = [
    SchemaFile {
        path: "docs/database/schema.sql",
        purpose: "tables, indexes and RLS policies",
        sql: include_str!("../../../docs/database/schema.sql"),
    },
    SchemaFile {
        path: "docs/database/cip-seed.sql",
        purpose: "cip_codes — 2,173 CIP 2020 codes",
        sql: include_str!("../../../docs/database/cip-seed.sql"),
    },
    SchemaFile {
        path: "docs/database/lookup-seed.sql",
        purpose: "the 7 IPEDS lookup tables",
        sql: include_str!("../../../docs/database/lookup-seed.sql"),
    },
    SchemaFile {
        path: "docs/database/programs-schema.sql",
        purpose: "stored-programs tables",
        sql: include_str!("../../../docs/database/programs-schema.sql"),
    },
    SchemaFile {
        path: "docs/database/program-lookup-seed.sql",
        purpose: "degree_types",
        sql: include_str!("../../../docs/database/program-lookup-seed.sql"),
    },
];

/// Every file concatenated in order, ready to pipe into `psql`.
///
/// Each file is introduced by a comment naming it, so a failure part-way through a long
/// run can be traced back to its source file rather than a line number in a 160 KB blob.
#[must_use]
pub fn concatenated() -> String {
    let mut out = String::with_capacity(total_bytes() + 512);
    out.push_str("-- Generated by `nuanalytics db bootstrap --print`.\n");
    out.push_str("-- Apply with: nuanalytics db bootstrap --print | psql \"$DATABASE_URL\"\n");
    out.push_str("-- Every object uses IF NOT EXISTS and drops policies before recreating\n");
    out.push_str("-- them, so this is safe to re-run against a live database.\n");
    for (index, file) in SCHEMA_FILES.iter().enumerate() {
        out.push_str("\n-- ============================================================\n");
        let _ = writeln!(
            out,
            "-- {}/{}  {}  ({})",
            index + 1,
            SCHEMA_FILES.len(),
            file.path,
            file.purpose
        );
        out.push_str("-- ============================================================\n");
        out.push_str(file.sql);
        if !file.sql.ends_with('\n') {
            out.push('\n');
        }
    }
    out
}

/// Combined size of the embedded SQL, used to size the concatenation buffer.
#[must_use]
pub fn total_bytes() -> usize {
    SCHEMA_FILES.iter().map(|f| f.sql.len()).sum()
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_embedded_file_has_content() {
        for file in &SCHEMA_FILES {
            assert!(
                file.sql.len() > 100,
                "{} embedded as {} bytes — a stub or a broken include",
                file.path,
                file.sql.len()
            );
        }
    }

    #[test]
    fn tables_are_created_before_they_are_seeded() {
        // The ordering constraint stated as the property it protects, rather than as a
        // fixed list: a seed that runs before its CREATE TABLE fails on a missing
        // relation, which is the specific error this module exists to prevent.
        let position = |needle: &str| {
            SCHEMA_FILES
                .iter()
                .position(|f| f.path.contains(needle))
                .unwrap_or_else(|| panic!("{needle} is not in the bootstrap order"))
        };
        assert!(
            position("schema.sql") < position("cip-seed.sql"),
            "cip_codes must exist before it is seeded"
        );
        assert!(
            position("schema.sql") < position("lookup-seed.sql"),
            "the lookup tables must exist before they are seeded"
        );
        assert!(
            position("programs-schema.sql") < position("program-lookup-seed.sql"),
            "degree_types must exist before it is seeded"
        );
    }

    #[test]
    fn the_bootstrap_order_covers_every_sql_file_shipped_for_setup() {
        // Catches a sixth file being added to docs/database/ without being wired in —
        // which would leave `db bootstrap` quietly producing an incomplete schema.
        // Files under historical/ are excluded by not recursing: they migrate databases
        // that predate a change and must never run on a fresh install.
        let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("docs/database");
        let mut on_disk: Vec<String> = std::fs::read_dir(&dir)
            .expect("docs/database exists")
            .filter_map(Result::ok)
            .map(|entry| entry.file_name().to_string_lossy().to_string())
            .filter(|name| {
                std::path::Path::new(name)
                    .extension()
                    .is_some_and(|e| e == "sql")
            })
            .collect();
        on_disk.sort();

        let mut registered: Vec<String> = SCHEMA_FILES
            .iter()
            .map(|f| {
                f.path
                    .rsplit('/')
                    .next()
                    .expect("path has a file name")
                    .to_string()
            })
            .collect();
        registered.sort();

        assert_eq!(
            on_disk, registered,
            "docs/database/*.sql and SCHEMA_FILES disagree — wire the new file into the \
             bootstrap order, or move it under docs/database/historical/ if it is a \
             migration for an existing database"
        );
    }

    #[test]
    fn concatenation_preserves_order_and_labels_each_file() {
        let combined = concatenated();
        let mut last = 0;
        for file in &SCHEMA_FILES {
            let at = combined
                .find(file.path)
                .unwrap_or_else(|| panic!("{} is not labelled in the output", file.path));
            assert!(at > last, "{} appears out of order", file.path);
            last = at;
        }
        assert!(
            combined.len() > total_bytes(),
            "the output should contain every file plus its headers"
        );
    }

    #[test]
    fn concatenation_is_safe_to_pipe_straight_into_psql() {
        let combined = concatenated();
        // A file not ending in a newline would glue its last statement to the next
        // file's leading comment, commenting the statement out.
        for file in &SCHEMA_FILES {
            let start = combined.find(file.sql).expect("file content is present");
            let after = start + file.sql.len();
            assert!(
                file.sql.ends_with('\n') || combined[after..].starts_with('\n'),
                "{} must be newline-terminated in the output",
                file.path
            );
        }
        assert!(
            combined.starts_with("--"),
            "the preamble must be a SQL comment, not prose psql would choke on"
        );
    }
}
