//! Database table models
//!
//! Rust structs corresponding to Supabase table schemas.

use serde::{Deserialize, Serialize};

/// Institution record from IPEDS HD survey
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Institution {
    /// IPEDS Unit ID (primary key)
    pub unitid: i32,
    /// Institution name
    pub name: String,
    /// City
    pub city: Option<String>,
    /// State abbreviation (e.g. "MA")
    pub state: Option<String>,
    /// Sector code (1=public 4yr, 2=private nonprofit 4yr, 3=for-profit 4yr, etc.)
    pub sector: Option<i32>,
    /// Control code (1=public, 2=private nonprofit, 3=for-profit)
    pub control: Option<i32>,
    /// Institution level (1=4-year, 2=2-year, 3=less-than-2-year)
    pub iclevel: Option<i32>,
    /// Carnegie classification (15=R1, 16=R2, 21=R1 in 2021 scheme, etc.)
    pub carnegie_class: Option<i32>,
    /// Historically Black College or University
    pub hbcu: Option<bool>,
    /// Tribal college or university
    pub tribal: Option<bool>,
    /// Locale code
    pub locale: Option<i32>,
    /// Institution size category
    pub inst_size: Option<i32>,
    /// Year this record was last updated from IPEDS
    pub updated_year: Option<i32>,
}

/// CIP code lookup record
///
/// Prefix queries (e.g. all `11.*` codes) are done via `starts_with` on the
/// `cip_code` field itself — no separate family columns needed.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CipCode {
    /// Full CIP code in dot notation (e.g. `"11.0101"`)
    pub cip_code: String,
    /// Human-readable program title
    pub title: String,
}

/// Completion record from IPEDS C survey (all CIP codes, primary and secondary majors)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Completion {
    /// Record ID (auto-generated by the database; omitted from INSERT payloads)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// IPEDS Unit ID
    pub unitid: Option<i32>,
    /// 6-digit CIP code with dot notation
    pub cip_code: Option<String>,
    /// Award level (see `award_levels` lookup table for labels)
    pub award_level: Option<i32>,
    /// Major number: 1=primary major, 2=second major (double-major)
    pub major_num: Option<i32>,
    /// Academic year (e.g. 2024 for 2023-2024)
    pub year: Option<i32>,
    /// Total completions
    pub total: Option<i32>,
    /// Total men
    pub total_men: Option<i32>,
    /// Total women
    pub total_women: Option<i32>,
    /// Nonresident alien men
    pub nonresident_alien_men: Option<i32>,
    /// Nonresident alien women
    pub nonresident_alien_women: Option<i32>,
    /// Hispanic men
    pub hispanic_men: Option<i32>,
    /// Hispanic women
    pub hispanic_women: Option<i32>,
    /// American Indian or Alaska Native men
    pub american_indian_men: Option<i32>,
    /// American Indian or Alaska Native women
    pub american_indian_women: Option<i32>,
    /// Asian men
    pub asian_men: Option<i32>,
    /// Asian women
    pub asian_women: Option<i32>,
    /// Black or African American men
    pub black_men: Option<i32>,
    /// Black or African American women
    pub black_women: Option<i32>,
    /// Native Hawaiian or Other Pacific Islander men
    pub native_hawaiian_men: Option<i32>,
    /// Native Hawaiian or Other Pacific Islander women
    pub native_hawaiian_women: Option<i32>,
    /// White men
    pub white_men: Option<i32>,
    /// White women
    pub white_women: Option<i32>,
    /// Two or more races men
    pub two_or_more_men: Option<i32>,
    /// Two or more races women
    pub two_or_more_women: Option<i32>,
    /// Race/ethnicity unknown men
    pub unknown_race_men: Option<i32>,
    /// Race/ethnicity unknown women
    pub unknown_race_women: Option<i32>,
}

/// Pre-aggregated completion totals for one institution, award level, and year.
///
/// Populated during `ingest_completions` in the same pass as the per-CIP rows.
/// Used as the fast denominator for demographic representation queries —
/// avoids scanning the full `completions` table on every MCP tool call.
///
/// `award_level = None` means the row covers all award levels combined.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InstitutionCompletionTotal {
    /// Record ID (auto-generated)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// IPEDS Unit ID
    pub unitid: Option<i32>,
    /// Award level (see `award_levels` lookup table); `None` = all levels
    pub award_level: Option<i32>,
    /// Academic year
    pub year: Option<i32>,
    /// Total completions across all CIP codes for this institution/level/year
    pub total: Option<i32>,
    /// Total men
    pub total_men: Option<i32>,
    /// Total women
    pub total_women: Option<i32>,
    /// Nonresident alien men
    pub nonresident_alien_men: Option<i32>,
    /// Nonresident alien women
    pub nonresident_alien_women: Option<i32>,
    /// Hispanic men
    pub hispanic_men: Option<i32>,
    /// Hispanic women
    pub hispanic_women: Option<i32>,
    /// American Indian or Alaska Native men
    pub american_indian_men: Option<i32>,
    /// American Indian or Alaska Native women
    pub american_indian_women: Option<i32>,
    /// Asian men
    pub asian_men: Option<i32>,
    /// Asian women
    pub asian_women: Option<i32>,
    /// Black or African American men
    pub black_men: Option<i32>,
    /// Black or African American women
    pub black_women: Option<i32>,
    /// Native Hawaiian or Other Pacific Islander men
    pub native_hawaiian_men: Option<i32>,
    /// Native Hawaiian or Other Pacific Islander women
    pub native_hawaiian_women: Option<i32>,
    /// White men
    pub white_men: Option<i32>,
    /// White women
    pub white_women: Option<i32>,
    /// Two or more races men
    pub two_or_more_men: Option<i32>,
    /// Two or more races women
    pub two_or_more_women: Option<i32>,
    /// Race/ethnicity unknown men
    pub unknown_race_men: Option<i32>,
    /// Race/ethnicity unknown women
    pub unknown_race_women: Option<i32>,
}

/// Stored degree program record
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StoredDegree {
    /// Auto-generated record ID
    pub id: Option<i64>,
    /// Unique degree identifier (e.g. "neu-khoury-bscs-2024")
    pub degree_id: String,
    /// IPEDS Unit ID of the institution
    pub unitid: Option<i32>,
    /// CIP code for this degree program
    pub cip_code: Option<String>,
    /// Catalog year (e.g. "2024-2025")
    pub catalog_year: Option<String>,
    /// Full degree YAML content
    pub yaml_content: String,
    /// Creation timestamp (ISO 8601)
    pub created_at: Option<String>,
}

/// Representation metrics for a demographic group
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DemographicRepresentation {
    /// Demographic group name
    pub group: String,
    /// Number of completions for this group
    pub completions: i64,
    /// Total completions across all groups
    pub total_completions: i64,
    /// Percentage of completions for this group
    pub completion_pct: f64,
    /// Number enrolled for this group (if available)
    pub enrolled: Option<i64>,
    /// Total enrolled (if available)
    pub total_enrolled: Option<i64>,
    /// Percentage of enrollment for this group (if available)
    pub enrollment_pct: Option<f64>,
    /// Representation ratio: `completion_pct` / `enrollment_pct` (1.0 = proportional)
    pub representation_ratio: Option<f64>,
}

#[cfg(test)]
mod tests {
    use super::*;

    /// [`Completion::id`] must be `#[serde(skip_serializing_if = "Option::is_none")]`
    /// so INSERT payloads omit `id` entirely. `PostgREST` rejects bulk INSERTs whose
    /// rows declare an `id` column the database is supposed to assign.
    #[test]
    fn test_completion_id_omitted_when_none() {
        let c: Completion = serde_json::from_value(serde_json::json!({
            "id": null,
            "unitid": 167_358,
            "cip_code": "11.0101",
            "award_level": 5,
            "major_num": 1,
            "year": 2024,
        }))
        .expect("minimal Completion JSON should deserialize");
        let json = serde_json::to_string(&c).expect("Completion should serialize");
        assert!(
            !json.contains("\"id\""),
            "id=None must be skipped in payload, got: {json}"
        );
    }

    #[test]
    fn test_institution_completion_total_id_omitted_when_none() {
        let t: InstitutionCompletionTotal = serde_json::from_value(serde_json::json!({
            "id": null,
            "unitid": 167_358,
            "award_level": 5,
            "year": 2024,
        }))
        .expect("minimal totals JSON should deserialize");
        let json = serde_json::to_string(&t).expect("totals should serialize");
        assert!(
            !json.contains("\"id\""),
            "id=None must be skipped in payload, got: {json}"
        );
    }
}
